version: "3"
services:
  componentization:
    image: componentization-war
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
#    networks:
#      - webnet
#networks:
#  webnet:
